// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class NativeFunctionsPigeonCodecReader: FlutterStandardReader {
}

private class NativeFunctionsPigeonCodecWriter: FlutterStandardWriter {
}

private class NativeFunctionsPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return NativeFunctionsPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return NativeFunctionsPigeonCodecWriter(data: data)
  }
}

class NativeFunctionsPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = NativeFunctionsPigeonCodec(readerWriter: NativeFunctionsPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol QRScannerApi {
  func startScanQRCode() throws
  func getLastScannedQRCode() throws -> String
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class QRScannerApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeFunctionsPigeonCodec.shared }
  /// Sets up an instance of `QRScannerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: QRScannerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startScanQRCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seek.QRScannerApi.startScanQRCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanQRCodeChannel.setMessageHandler { _, reply in
        do {
          try api.startScanQRCode()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      startScanQRCodeChannel.setMessageHandler(nil)
    }
    let getLastScannedQRCodeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seek.QRScannerApi.getLastScannedQRCode\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLastScannedQRCodeChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getLastScannedQRCode()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getLastScannedQRCodeChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BiometricAuthApi {
  func isBiometricAvailable() throws -> Bool
  func authenticate() throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BiometricAuthApiSetup {
  static var codec: FlutterStandardMessageCodec { NativeFunctionsPigeonCodec.shared }
  /// Sets up an instance of `BiometricAuthApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BiometricAuthApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let isBiometricAvailableChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seek.BiometricAuthApi.isBiometricAvailable\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isBiometricAvailableChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isBiometricAvailable()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isBiometricAvailableChannel.setMessageHandler(nil)
    }
    let authenticateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seek.BiometricAuthApi.authenticate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      authenticateChannel.setMessageHandler { _, reply in
        do {
          try api.authenticate()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      authenticateChannel.setMessageHandler(nil)
    }
  }
}
